### ISSUE TITLE
disambiguita : stato eventi

### ISSUE THREAD

**Issue by federicopessina** [federicopessina/UnigeSocialSportDB#14]
ogni	 evento	 dispone	 di	 ...	uno	stato	(APERTO/CHIUSO)

Ogni iscrizione	...	 associata	 a	 uno	 stato (CONFERMATO/RIFIUTATO),

ci si confonde

quindi ho cambiato la colonna con e_aperto (booleano) nella tabella eventi
la tabella iscrizione_eventi andrà a vedere la tabella eventi per vedere se questo è aperto alle iscrizioni o meno
va aggiunto alle disambiguità

**Comment by lavi24lavi** [comment]
ho aggiunto una riga di testo in cui dico di non confondere i due campi

**Comment by federicopessina** [comment]
ottimo, chiudo la issue
