### ISSUE TITLE
sponsor 

### ISSUE THREAD

**Issue by federicopessina** [federicopessina/UnigeSocialSportDB#25]
specificare che è un vettore perchè non è lo scopo dell'applicazione salvare gli sponsor, quindi abbiamo deciso di utilizzare un vettore. se lo richiedesse (di dover querare spesso sugli sponsor) bisognerebbe fare una tabella a parte con (torneo_id, sponsor) con entrambi i campi primary key

**Comment by lavi24lavi** [comment]
va bene mettiamolo come vettore

**Comment by federicopessina** [comment]
specifichiamolo nelle chiarificazioni.

chiudo la issue @lavi24lavi
